// auto generated by go tool dist

package sys

const DefaultGoroot = `/tmp/appengine/go_appengine/goroot`
const TheVersion = `go1.6.3 (appengine-1.9.48)`
const Goexperiment = ``
const StackGuardMultiplier = 1

